models:
  - type: main
    engine: openai
    model: meta/llama-3.1-8b-instruct
    parameters:
      openai_api_base: http://localhost:8000/v1
      openai_api_key: nim-local
      temperature: 0.0

rails:
  output:
    flows:
      - check wiki style

prompts: []
